apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
                - staging
                - prod

  template:
    metadata:
      name: metallb-{{name}}
    spec:
      project: infra
      source:
        repoURL: https://github.com/erickmpene/k8s-enterprise-1.git
        targetRevision: main
        path: infra/metallb/chart
        helm:
          valueFiles:
            - ../values-{{name}}.yaml
      destination:
        server: '{{server}}'
        namespace: metallb-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      info:
        - name: Managed by
          value: ArgoCD with Helm
        - name: Purpose
          value: Deploy MetalLB with per-cluster IP pools
      ignoreDifferences:
        - group: ""
          kind: ConfigMap
          jsonPointers:
            - /data/config
      healthChecks:
        - group: apps
          kind: Deployment
          name: controller
          namespace: metallb-system
          health.lua: |
            hs = {}
            if obj.status ~= nil and obj.status.readyReplicas == obj.status.replicas then
              hs.status = "Healthy"
              hs.message = "MetalLB Controller is ready"
            else
              hs.status = "Progressing"
              hs.message = "Waiting for controller to be ready"
            end
            return hs
