namespaceOverride: metallb-system
replicaCount: 3

controller:
  logLevel: info

speaker:
  logLevel: info

configInline:
  address-pools:
    - name: prod
      protocol: layer2
      addresses:
        - 192.168.1.47-192.168.1.49
