# === Chart 'gateway' ===
gateway:
  hub: docker.io/istio
  tag: 1.26.0

  image:
    repository: auto
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    ports:
      - name: http2
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443

  deployment:
    podAnnotations:
      debug/check: "enabled"
    containers:
      - name: istio-proxy
        ports:
          - containerPort: 8080
            name: http
          - containerPort: 8443
            name: https


_internal_defaults_do_not_set:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "15014"


