namespaceOverride: istio-system
controller:
  logLevel: info
speaker:
  logLevel: info

# Chart: istio/base
base:
  enabled: true

# Chart: istio/istiod (control plane)
istiod:
  enabled: true
  global:
    istioNamespace: istio-system

# Chart: istio/gateway (alias: istio-ingress)
istio-ingress:
  enabled: true
  name: istio-ingress
  image:
    repository: docker.io/istio/proxyv2
    tag: 1.25.2
  autoscaleEnabled: false
  replicaCount: 1
  service:
    type: LoadBalancer
    ports:
      - name: http2
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443
  labels:
    istio: ingressgateway
