apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notylus-com-dev
  namespace: argocd
spec:
  project: notylus.com
  source:
    repoURL: git@github.com:erickmpene/k8s-enterprise-1.git
    targetRevision: main
    path: applications/notylus.com/app-of-apps/dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true