apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-ingress-controller-multicluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
                - staging
                - prod

  template:
    metadata:
      name: ingress-controller-nginx-{{name}}
    spec:
      project: infra
      source:
        repoURL: https://github.com/erickmpene/k8s-enterprise-1.git
        targetRevision: main
        path: /infra/ingress-controller-nginx/chart
        helm:
          valueFiles:
            - ../values-{{name}}.yaml
      destination:
        server: '{{server}}'
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
