namespaceOverride: ingress-nginx
controller:
  replicaCount: 2
  ingressClassResource:
    name: nginx
    enabled: true
  ingressClass: nginx
  service:
    type: LoadBalancer  # ou NodePort si bare-metal sans MetalLB
