namespaceOverride: ingress-nginx
controller:
  replicaCount: 3
  ingressClassResource:
    name: nginx
    enabled: true
  ingressClass: nginx
  service:
    type: ClusterIP
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  config:
    use-proxy-protocol: "true"
  extraArgs:
    enable-real-ip: ""
    set-real-ip-from: "0.0.0.0/0"
    real-ip-header: "proxy_protocol"

terminationGracePeriodSeconds: 300