namespaceOverride: ingress-nginx
controller:
  replicaCount: 1
  ingressClassResource:
    name: nginx
    enabled: true
  ingressClass: nginx
  service:
    type: ClusterIP  # ou NodePort si bare-metal sans MetalLB
