apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-1.kingakati.com-prod
  namespace: argocd
spec:
  project: site-1.kingakati.com
  source:
    repoURL: git@github.com:erickmpene/k8s-enterprise-1.git
    targetRevision: main
    path: applications/site-1.kingakati.com/app-of-apps/prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
