apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-1.kingakati.com-prod-web
  namespace: argocd
spec:
  project: site-1.kingakati.com
  source:
    repoURL: git@github.com:erickmpene/k8s-enterprise-1.git
    targetRevision: main
    path: applications/site-1.kingakati.com/web/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: site-1.kingakati.com-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
