apiVersion: v2
name: metallb-wrapper
description: Helm wrapper to deploy metallb via GitOps
version: 0.1.0

dependencies:
  - name: metallb
    version: 0.14.9
    repository: https://metallb.github.io/metallb
