apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notylus-com-cert
  namespace: notylus-com
spec:
  secretName: PLACEHOLDER
  commonName: PLACEHOLDER
  dnsNames:
    - PLACEHOLDER
  issuerRef:
    name: PLACEHOLDER
    kind: Issuer
