apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: notylus-com-issuer
  namespace: istio-system
spec:
  acme:
    email: PLACEHOLDER
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: PLACEHOLDER
    solvers:
      - http01:
          ingress:
            class: nginx
