apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-multicluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
                - staging
                - prod
  template:
    metadata:
      name: cert-manager-{{name}}
    spec:
      project: cert-manager
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: 1.14.4
        helm:
          valueFiles:
            - values-{{name}}.yaml  # utilisé dans ton repo Git
          values: |
            installCRDs: true
      destination:
        server: '{{server}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
