apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-multicluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
                - staging
                - prod
  template:
    metadata:
      name: cert-manager-{{name}}
    spec:
      project: infra
      source:
        repoURL: git@github.com:erickmpene/kubernetes-gitops-repo.git
        targetRevision: main
        path: infra/cert-manager
        helm:
          valueFiles:
            - values-{{name}}.yaml
          values: |
            installCRDs: true
      destination:
        server: '{{server}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
