apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: Projet pour tous les composants d'infrastructure (cert-manager, ingress, istio, metallb)

  sourceRepos:
    - https://charts.jetstack.io
    - https://kubernetes.github.io/ingress-nginx
    - https://charts.istio.io
    - https://metallb.github.io/metallb
    - https://github.com/erickmpene/k8s-enterprise-1.git 
  destinations:
    - namespace: cert-manager
      server: '*'
    - namespace: ingress-nginx
      server: '*'
    - namespace: istio-system
      server: '*'
    - namespace: metallb-system
      server: '*'
    - namespace: kube-system
      server: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: false
