apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-1.kingakati.com-staging-certs
  namespace: argocd
spec:
  project: site-1.kingakati.com
  source:
    repoURL: git@github.com:erickmpene/k8s-enterprise-1.git
    targetRevision: main
    path: applications/site-1.kingakati.com/certs/overlays/staging
  destination:
    server: https://k8s.staging.notylus.com:6443
    namespace: site-1-kingakati-com
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true