apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notylus-com-prod-web
  namespace: argocd
spec:
  project: notylus.com
  source:
    repoURL: git@github.com:erickmpene/k8s-enterprise-1.git
    targetRevision: main
    path: applications/notylus.com/web/overlays/prod
  destination:
    server: https://kbs.notylus.com:6443
    namespace: notylus.com
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
