apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: site-1.kingakati.com-cert
spec:
  secretName: site-1.kingakati.com-dev-tls-secret
  commonName: dev.site-1.kingakati.com
  dnsNames:
    - dev.site-1.kingakati.com
  issuerRef:
    name: site-1.kingakati.com-dev-issuer
