apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-multicluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
                - staging
                - prod
  template:
    metadata:
      name: istio-{{name}}
    spec:
      project: infra
      source:
        repoURL: https://github.com/erickmpene/k8s-enterprise-1.git
        targetRevision: main
        path: infra/istio/envs/{{name}}
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      info:
        - name: Managed by
          value: ArgoCD with Helm
        - name: Purpose
          value: Deploy istio per-cluster
