apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-1.kingakati.com-dev-certs
  namespace: argocd
spec:
  project: site-1.kingakati.com
  source:
    repoURL: git@github.com:erickmpene/k8s-enterprise-1.git
    targetRevision: main
    path: applications/site-1.kingakati.com/certs/overlays/dev
  destination:
    server: https://kbs.notylus.com:6443
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
