apiVersion: v2
name: ingress-controller-wrapper
description: Helm wrapper to deploy Ingress Controller Nginx via GitOps
version: 0.1.0

dependencies:
  - name: ingress-nginx
    version: 4.12.1
    repository: https://kubernetes.github.io/ingress-nginx
