apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notylus-com
  name: notylus-com
  namespace: notylus-com
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notylus-com

  template:
    metadata:
      labels:
        app: notylus-com
    spec:
      containers:
      - image: PLACEHOLDER
        name: notylus-com
        ports:
        - containerPort: 5678
        resources: {}
status: {}
