apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: site-1.kingakati.com-issuer
  namespace: cert-manager
spec:
  acme:
    email: PLACEHOLDER
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: PLACEHOLDER
    solvers:
      - http01:
          ingress:
            class: nginx
