apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notylus-com-cert
  namespace: istio-system
spec:
  secretName: notylus-com-prod-tls-secret
  commonName: prod.notylus.com
  dnsNames:
    - prod.notylus.com
  issuerRef:
    name: notylus-com-issuer
