apiVersion: v2
name: nfs-dev-wrapper
description: Helm wrapper to deploy nfs-provisioner via GitOps
version: 0.1.0

dependencies:
  - name: nfs-subdir-external-provisioner
    version: 4.0.18
    repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
