namespaceOverride: nfs-provisioner
controller:
  logLevel: info
speaker:
  logLevel: info

nfs:
  server: 192.168.1.170
  path: /srv/nfs/cluster-prod
  volumeName: nfs-subdir-external-provisioner-root
  reclaimPolicy: Retain

storageClass:
  name: nfs-prod
  defaultClass: false
