apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-istio
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: contact@notylus.com
    privateKeySecretRef:
      name: letsencrypt-istio-account-key
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            - name: istio-ingressgateway
              namespace: istio-system
