apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: site-1.kingakati.com-staging-cert
spec:
  secretName: site-1.kingakati.com-staging-tls-secret
  commonName: site-1.kingakati.com
  dnsNames:
    - site-1.kingakati.com
  issuerRef:
    name: site-1.kingakati.com-staging-issuer
