apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: site-vitrine-site-1-kingakati-com
  name: site-vitrine
  namespace: site-1-kingakati-com
spec:
  replicas: 5
  selector:
    matchLabels:
      app: site-vitrine-site-1-kingakati-com
  strategy: {}
  template:
    metadata:
      labels:
        app: site-vitrine-site-1-kingakati-com
    spec:
      containers:
      - image: PLACEHOLDER
        name: site-vitrine
        ports:
        - containerPort: 8080
        resources: {}
status: {}
