# namespaceOverride: istio-system
# controller:
#   logLevel: info
# speaker:
#   logLevel: info

image:
  repository: docker.io/istio/proxyv2
  tag: 1.26.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  ports:
    - name: http2
      port: 81
      targetPort: 8080

labels:
  debug-source: from-values-yaml

deployment:
  podAnnotations:
    debug/check: "yes"
  containers:
    - name: istio-proxy
      ports:
        - containerPort: 8080
          name: http


