# namespaceOverride: istio-system
# controller:
#   logLevel: info
# speaker:
#   logLevel: info

istio-ingress:
  image:
    repository: docker.io/istio/proxyv2
    tag: 1.26.0
  service:
    type: LoadBalancer
    ports:
      - name: http2
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443
  deployment:
    podAnnotations:
      debug/check: "yes"


